type ProductType = {
    id: number,
    gallery: string[],
    image: string,
    thumbnail?: string,
    img_links: string[],
    title: string,
    brand: string,
    price: string,
    old_price: string,
    description: string,
    hot_deal: boolean,
    special_offer: boolean,
    views: string,
    product_rating: string,
    slug: string,
    sku: string,
    stock_qty: string,
    shipping_amount: string,
    category: string,
}